### PR TITLE
feat: support for multi-stage builds

### LINKED ISSUE #74: Support Multi Stage Builds
Shows error when using [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).

The line with second `FROM` shows error.

screen shot 2017-06-29 at 3 15 45 pm

### PR DESCRIPTION
**Pull request by nexdrew**
Fixes #74.

The first commit adds tests for multi-stage builds (examples taken from [Docker's documentation](https://docs.docker.com/engine/userguide/eng-image/multistage-build/)), which should fail.

The subsequent commits modify logic to get the tests to pass.

Instead of failing on each subsequent `FROM` command, the logic now considers this as the beginning of a new build stage (as modeled by internal state during instructions processing).

**NOTE:** This should probably be considered a BREAKING CHANGE, since Dockerfiles containing more than one `FROM` command will no longer fail linting, which will be problematic if the (unspecified) target Docker version is less than 17.05. We could potentially get around this by introducing a way (e.g. CLI/config option or auto env detection) to specify/detect the Docker version, but this seems out-of-scope for this PR.

Also note that this change **does not** add any new checks specific to multi-stage Dockerfiles, such as potentially checking that a stage has more than just a single `FROM` command. Even so, the changes represented here could be considered a necessary first step, allowing stage-specific checks to be added later.

### CODE REVIEW

**Comment by nexdrew** [comment]
@marccampbell @emosbaugh Would love a review of this if you get a chance. 😎

**Comment by nexdrew** [comment]
@emosbaugh Thanks for the quick turnaround! Will wait to hear from #74 commenters before I proceed.

**Comment by nexdrew** [comment]
@marccampbell @emosbaugh Thoughts on making this a major version bump? This question is the only reason I'm hesitant to merge and release this right now.

**Comment by emosbaugh** [comment]
i see no reason to bump major version. no big refactor or anything and nothing incompatible or api changes

**Comment by nexdrew** [comment]
@emosbaugh 

> i see no reason to bump major version. no big refactor or anything and nothing incompatible or api changes

Fair enough. I'll merge and release as a minor update then. Thanks!

**Comment by nexdrew** [comment]
Published to npm as 1.4.0.

**Pull request merged**
